---
# ServiceAccount para que Jenkins ejecute pods en el namespace staging
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-agent
  namespace: staging
---
# Role con permisos para que Jenkins maneje pods
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-agent-role
  namespace: staging
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "pods/status"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
---
# RoleBinding para asociar el ServiceAccount con el Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-agent-rolebinding
  namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-agent-role
subjects:
- kind: ServiceAccount
  name: jenkins-agent
  namespace: staging
---
# Secret para generar el token del ServiceAccount (K8s 1.24+)
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-agent-token
  namespace: staging
  annotations:
    kubernetes.io/service-account.name: jenkins-agent
type: kubernetes.io/service-account-token
